### ISSUE TITLE
PIPE Scan Issue

### ISSUE THREAD

**Issue by SammySharma** [pkjmesra/PKScreener#111]
Even though i installed the latest Docker image , i am not getting piped scanner. Any Suggestion on this would be really helpful.
![image](https://github.com/pkjmesra/PKScreener/assets/137750522/a9bab99a-f81e-40a1-9db1-ae4d6338bca7)

**Comment by pkjmesra** [comment]
@SammySharma 

I've pushed an update for docker build targeted at both amd64 and arm64 processor architectures.

1. Download and install docker desktop: https://docs.docker.com/get-docker/
2. After installation, launch/run docker desktop and if it asks, login using your docker credentials.
3. Launch any command line (for example, cmd on windows or terminal on Mac) 
4. Type and run : `docker pull pkjmesra/pkscreener:latest` 
5. Then type `docker run -it pkjmesra/pkscreener:latest`
The option -i will open the pkscreener in interactive mode within docker. -t will allocate a pseudo terminal for you so you can begin to use pkscreener

Let me know how that goes.

**Comment by SammySharma** [comment]
Thank you very much @pkjmesra , I will try that for sure.
