### ISSUE TITLE
Provide of the real time data from 9:00AM only

### ISSUE THREAD

**Issue by raviyellani** [pkjmesra/PKScreener#113]
Requesting a feature of getting the Realtime data from 9:00AM instead of 9:15 Am for analysing the premarket open data of the stocks.

Currently after 9:15 only we are getting real time data before that only cached

**Comment by pkjmesra** [comment]
@raviyellani - Fixed this in d0bc9fef82b3f108fe7789751381cc7d1d0a6a78 . pkscreener.ini now contains 
```
marketopen = 09:15
marketclose = 15:30
```

You can change this as per your convenience https://github.com/pkjmesra/PKScreener/blob/095d871bfc1fb2a905436f801d2dfba913f23d19/pkscreener.ini#L18
