### ISSUE TITLE
Issue in pulling docker image: Docker - Failed to register layer: max depth exceeded

### ISSUE THREAD

**Issue by saxenachaitanya** [pkjmesra/PKScreener#117]
**Is your feature request related to a problem? Please describe.**
When I'm pulling docker image it's giving me below error 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
<img width="563" alt="epicpen_PXbgu3SRtf" src="https://github.com/pkjmesra/PKScreener/assets/79158161/f5e5a753-b005-4ab9-9f5d-aec337c5c059">

**Comment by a54000** [comment]
Facing same issue..

**Comment by pkjmesra** [comment]
@saxenachaitanya - Do you still face problem pulling from dockerhub ?

**Comment by pkjmesra** [comment]
By naming the base built image pkjmesra/pkscreener:latest in Dockerfile_base which is the same as the FROM pkjmesra/pkscreener:latest image in the Dockerfile, Docker was layering the build on top of itself each time.

The original build started on the "base" pkjmesra/pkscreener:latest but then each subsequent build would start from the local pkjmesra/pkscreener:latest image which had been appended to, until eventually we hit the maximum number of layers for the storage driver.

I have tried to fix this by tagging the base image pkjmesra/pkscreener:base and then building the actual image with :latest tag. I think it should fix the problem.

@saxenachaitanya, @srikanthlogic, @a54000
