### ISSUE TITLE
Cache data creating issue in real market timing

### ISSUE THREAD

**Issue by raviyellani** [pkjmesra/PKScreener#118]
Due to the cache data timings or any other bug, the data is not properly updated in the real market timing some the screener are showing yesterday data only during market hours also

Recommended to remove the cache data and any time we can the live market data as fetching data is quick only, not taking much time for it

**Comment by pkjmesra** [comment]
@raviyellani - Can you capture an example and post here ? Also, you can always disable cache in the pkscreener.ini file by turning 
```
cachestockdata = y
```
to
```
cachestockdata = n
```
