### ISSUE TITLE
Intraday Breakout setup at Day Open

### ISSUE THREAD

**Issue by kohli0101** [pkjmesra/PKScreener#120]
Timeframe = 1m, 5m, 10m, 15m, 30m
(Start time = 09:15:01AM,
For example : 5m candle is 09:15:01AM to 09:19:59AM)

For Long Side Breakout

Open price = Low price
Open price < Previous Day high price
Close price > Previous Day High price

For short Side Breakdown

Open price = High price
Open price > Previous Day Low price
Close price < Previous Day Low price

![IMG-20240703-WA0021](https://github.com/pkjmesra/PKScreener/assets/109454493/02efb8f5-0b5a-42a3-b9c9-b6e889c9709a)

**Comment by pkjmesra** [comment]
Feature will be made available in build# 455 and above.
