### ISSUE TITLE
PRICE AND VOLUME BREAKOUT (Enhancement)

### ISSUE THREAD

**Issue by raviyellani** [pkjmesra/PKScreener#121]
Nth minute not working , so once check with below logic 

IF BY 9.30AM ANY STOCK OPENS OR RISES BY 1% COMPARED TO PREVIOUS CLOSE  AND ALSO
TOTAL VOLUMES RISES BY 5% OF PREVIOUS DAYS VOLUME

**Comment by pkjmesra** [comment]
Thanks @raviyellani for reporting this. It has been fixed in the recent release build #463 and above.
