### ISSUE TITLE
Sectoral Indexes

### ISSUE THREAD

**Issue by mukundg920** [pkjmesra/PKScreener#122]
Hey, 
The screener is working aboslutely awesome the way it is created. I just wanted if we could have a add on, if you have access to Sectoral Indexes (Ex- NIFTY IT/REAL ESTATE/AUTO/FMCG etc etc.) can we run the Scanners over them as well? 
I just want to know those whenever they are forming VCP (7>4). Would be glad to see if it works out.
Thanks in advance

**Comment by pkjmesra** [comment]
@mukundg920 
At this time, you can choose index option 0 and then , when prompted, enter ^CNXNIFTY or ^CNXAUTO or ^NSEBANK, ^CNXFIN etc.

However, it will show all results without filtering for the selected scanner (e.g 7 > 4 or VCP). I'll have that implemented soon.

**Comment by pkjmesra** [comment]
@mukundg920 - Please try and release build # 457 and above and try the menus X > S > choose whatever index you'd like and go on to choose scanners.

**Comment by pkjmesra** [comment]
You can choose X (Scanners) > S (Sectoral Indices) > All of the above > 7 (chart patterns) > 4 (VCP) :
<img width="1267" alt="Screenshot 2024-07-11 at 11 40 22 AM" src="https://github.com/pkjmesra/PKScreener/assets/1358101/4b601b25-174c-4d38-a6a4-bf54a531a95b">
