### ISSUE TITLE
Nth minute Price and Volume breakout not working (Bug)

### ISSUE THREAD

**Issue by raviyellani** [pkjmesra/PKScreener#123]
15 min Price and volume breakout not working for any cater gory once kindly check the logic  whenever the 15 min time frame the next candle volume is above the previous candle volume around 2 or 3 percent the and price is moved higher than the previous close we can generate alert (combining with technical will work good)

**Comment by pkjmesra** [comment]
Thanks @raviyellani for reporting this. It has been fixed in the recent release build #463 and above.
