### ISSUE TITLE
VCP

### ISSUE THREAD

**Issue by kohli0101** [pkjmesra/PKScreener#137]
VCP + AVWAP screener

Stock should be having VCP
Price should not be too far from AVWAP
Price should close above AVWAP by crossing it in daily timeframe would be best.
AVWAP should be flat (like straight line type)

**Comment by pkjmesra** [comment]
Fixed in 6887dbc2b5fc8f061868d4d3589f5a83fc571a40 and released under build : 477 and above. Try out option X > 12 > 34 or piped scanner : P_1_22 or P_1_23
