### ISSUE TITLE
Unable to open PKSCREENER

### ISSUE THREAD

**Issue by SammySharma** [pkjmesra/PKScreener#14]
Hi There,
I followed the guide for Windows System however i am not able to run the application.
When i tried to open pkscreenercli.py , it opens for a second and closed automatically.

**Comment by pkjmesra** [comment]
@SammySharma - Open a command prompt and launch pkscreener with -l switch. For example:

pkscreener.exe -l

-l is for log collection. Then zip and attach the logs here. The logs will be generated under pkscreener folder in the temp directory. When you launch, it will show you the path where it will collect all the logs.

**Comment by pkjmesra** [comment]
Hello, I didn't hear any further comment from you. Closing this issue @SammySharma ! Feel free to reopen if this issue still persists for you.
