### ISSUE TITLE
piped scanner saving of the excel with the name of the last scanner instead of with piped scanner number (Feature)

### ISSUE THREAD

**Issue by raviyellani** [pkjmesra/PKScreener#140]
piped scanner saving of the excel with the name of the last scanner instead of with piped scanner number, has there are multiple excel files are saving the results folder for piped scanner cannot able to determine which belong to which scanner , when multiple piped scanners excecuted

https://github.com/user-attachments/assets/bbdfe85c-c091-4006-8176-dc0edcaf57f5

**Comment by pkjmesra** [comment]
Fixed in bad0d3db56885bd3e1e0a1e7eda6e30d275f8def
Release build : 480
