### ISSUE TITLE
Open low equal

### ISSUE THREAD

**Issue by Saj250** [pkjmesra/PKScreener#152]
Screener related to open low equal should be introduced
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pkjmesra** [comment]
@Saj250 - Please look for menu option X > 12 > 32 (Intraday Breakout/Breakdown setup). It already has Open=low setup.

See today's results, for example:

<img width="903" alt="Screenshot 2024-08-22 at 2 37 40 PM" src="https://github.com/user-attachments/assets/a5a349db-4545-4498-9efc-979aa4c833a8">
