### ISSUE TITLE
Price crossing 200 EMA from below on monthly chart should be added

### ISSUE THREAD

**Issue by Saj250** [pkjmesra/PKScreener#153]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pkjmesra** [comment]
>> 200 EMA from below on monthly chart
On monthly chart, 200 EMA will need 200*12 = 2400 month's data, which is 200 years :-)
Please try X > 12 > 40 and choose your parameters to select SMA/EMA and price cross from above/below the MAs.
