### ISSUE TITLE
Include a new menu option called Data Downloads, that will allow downloading NSE Symbols

### ISSUE THREAD

**Issue by pkjmesra** [pkjmesra/PKScreener#159]
Include a new menu option called **Data Downloads**, that will allow downloading such and other data for other consumption purposes.

**Comment by pkjmesra** [comment]
Partially enabled it using `Data Downloads` menu: 2ada6cdcded7823ded40e8be2c1ed60277ee6bdc
<img width="884" alt="Screenshot 2024-08-30 at 1 22 27 PM" src="https://github.com/user-attachments/assets/487a5ced-a580-436b-88ab-c64f93bbbcbc">

The submenu for data downloads:
<img width="589" alt="Screenshot 2024-08-30 at 1 22 42 PM" src="https://github.com/user-attachments/assets/fe4c0a64-ba4b-4676-bc60-9df92bf9b5ba">

The submenu for NSE symbols data downloads
<img width="484" alt="Screenshot 2024-08-30 at 1 22 54 PM" src="https://github.com/user-attachments/assets/2660f38c-bb08-4ab7-841c-fcc1ddd6a8d6">

And the symbols data downloaded success message:
<img width="719" alt="Screenshot 2024-08-30 at 1 23 09 PM" src="https://github.com/user-attachments/assets/262e1b8d-498c-435f-9a3c-138d95dcf6cf">

@markethacks_databhai - Will this uffice?

**Comment by pkjmesra** [comment]
Fixed with sector/industry info: 723360325a8c13635f1b773394538688346dd0aa

**Comment by markethacks** [comment]
thanks a lot bro, very much appreciated! will try it.
