### ISSUE TITLE
Add "Bullish Today for Previous Day Open/Close (PDO/PDC) with 1M Volume" as a new scan

### ISSUE THREAD

**Issue by keithevans786** [pkjmesra/PKScreener#163]
Please add this as a new screener option in the app 
![IMG_20240831_150918_916.jpg](https://github.com/user-attachments/assets/0eaebf68-c7e7-449a-b158-2dd304c9b7f1)

**Comment by pkjmesra** [comment]
Fixed 08ae89e9b7f7bcc217e5170a61429fcdd6fc5e5b
