### ISSUE TITLE
Software closed after completion of piped screener 

### ISSUE THREAD

**Issue by sanjay-mech** [pkjmesra/PKScreener#164]
After completing the piped screener, pressing enter closes the entire screen. Could you please add an option to return to the main menu instead?
Because of this need to start software everytime,which is time consuming.
Thanks

**Comment by pkjmesra** [comment]
Fixed in aefa9e63bd8e148d0ff5443f18509fa36dfd7d88

**Comment by pkjmesra** [comment]
Fixed in the latest release: build number 532 and above.
