### ISSUE TITLE
Tool Screen Exits after running Piped Scanners

### ISSUE THREAD

**Issue by sandykools** [pkjmesra/PKScreener#165]
**Describe the bug**
After running the piped scanners on the tool, it asks to Input M to go back to main screen.
When pressed M, it is showing pipe results and asking to press enter to exit. 

![image](https://github.com/user-attachments/assets/7d158e53-c917-4399-9ed4-7ddc0862dcd9)

**Expected behavior**
Screen should go back to the main Page. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser [e.g. chrome, safari] . CMD - Docker
![Screenshot 2024-09-01 153654](https://github.com/user-attachments/assets/6e3b1ee4-1785-4ca7-af72-d1aab2b21a8f)

**Comment by pkjmesra** [comment]
To be fixed along with #164

**Comment by pkjmesra** [comment]
Fixed in aefa9e63bd8e148d0ff5443f18509fa36dfd7d88

**Comment by pkjmesra** [comment]
Fixed in the latest release: build number 532 and above.
