### ISSUE TITLE
Tool does not work after the recent upgrade in Docker

### ISSUE THREAD

**Issue by sandykools** [pkjmesra/PKScreener#174]
Tool do not produce any options to run screener. Just display the initial screen. Below are the error messages in the container log:

{"log":"\rsetterm: terminal xterm does not support --store\r\n","stream":"stdout","time":"2024-09-03T18:48:59.239769685Z"}
{"log":"\u001b[37m\u001b[40m\u001b[H\u001b[2J\u001b[3J\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[92m\r\n","stream":"stdout","time":"2024-09-03T18:48:59.242396643Z"}
{"log":"   _______   __   ___   ________  ______    _______    _______   _______  _____  ___    _______   _______TM 🇮🇳\r\n","stream":"stdout","time":"2024-09-03T18:48:59.24242583Z"}
{"log":"  |   __ \"\\ |/\"| /  \") /\"       )/\" _  \"\\  /\"      \\  /\"     \"| /\"     \"|(\"   \\|\"  \\  /\"     \"| /\"      \\  \r\n","stream":"stdout","time":"2024-09-03T18:48:59.242431368Z"}
{"log":"  (. |__) :)(: |/   / (:   \\___/(: ( \\___)|:        |(: ______)(: ______)|.\\   \\    |(: ______)|:        |\r\n","stream":"stdout","time":"2024-09-03T18:48:59.242436588Z"}
{"log":"  |:  ____/ |    __/   \\___  \\   \\/ \\     |_____/   ) \\/    |   \\/    |  |: \\.   \\  | \\/    |  |_____/   )\r\n","stream":"stdout","time":"2024-09-03T18:48:59.242440677Z"}
{"log":"  (|  /     (// _  \\    __/  \\  //  \\ _   //      /  // ___)_  // ___)_ |.  \\    \\. | // ___)_  //      /\r\n","stream":"stdout","time":"2024-09-03T18:48:59.2424448Z"}
{"log":" /|__/ \\    |: | \\  \\  /\" \\   :)(:   _) \\ |:  __   \\ (:      \"|(:      \"||    \\    \\ |(:      \"||:  __   \\ \r\n","stream":"stdout","time":"2024-09-03T18:48:59.242449385Z"}
{"log":"(_______)   (__|  \\__)(_______/  \\_______)|__|  \\___) \\_______) \\_______) \\___|\\____\\) \\_______)|__|  \\___)\r\n","stream":"stdout","time":"2024-09-03T18:48:59.242453612Z"}
{"log":"\r\n","stream":"stdout","time":"2024-09-03T18:48:59.242458067Z"}
{"log":"v0.45.20240903.536\u001b[0m | NIFTY 50 | Closed | 2024-09-03 | 25279.85 | \u001b[92m▲1.15\u001b[0m (\u001b[92m0.0\u001b[0m%) | S\u0026P BSE SENSEX | Closed | 2024-09-03 | 82555.44 | \u001b[91m▼-4.4\u001b[0m (\u001b[91m-0.01\u001b[0m%) | Next Bell: \u001b[93m2024-09-04 09:15:00\u001b[0m\r\n","stream":"stdout","time":"2024-09-03T18:48:59.242479878Z"}
{"log":"\r\n","stream":"stdout","time":"2024-09-03T18:48:59.242485037Z"}

![Screenshot from 2024-09-04 01-00-13](https://github.com/user-attachments/assets/5afdf9ab-bcaa-4a8f-b34b-9064cf758f95)

**Comment by pkjmesra** [comment]
Working fine. Please take latest pull and try again!
