### ISSUE TITLE
MarketHours class is missing. While running locally it is giving error 

### ISSUE THREAD

**Issue by BalachandraRaju** [pkjmesra/PKScreener#175]
**Describe the bug**
    import pkscreener.classes.ConfigManager as ConfigManager
  File "myenv/lib/python3.10/site-packages/pkscreener/classes/ConfigManager.py", line 36, in <module>
    from PKDevTools.classes.MarketHours import MarketHours
ModuleNotFoundError: No module named 'PKDevTools.classes.MarketHours'

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pkjmesra** [comment]
Please install PKDevTools @BalachandraRaju
