### ISSUE TITLE
Enable Auto-save/Save as Excel feature for Back-testing Results

### ISSUE THREAD

**Issue by sandykools** [pkjmesra/PKScreener#177]
**Is your feature request related to a problem? Please describe.**
When we run back testing, there is no option to save the results to excel. 

**Describe the solution you'd like**
As we get 3 types of output when we the backtesting, please enable feature to save all three outputs with backtest name, days we backtested, scanner name etc to the file name. At least if we add any special char to the output it would be easy for copy paste and format

**Describe alternatives you've considered**
Saved it to excel by copying the results but formatting the results is tough as we have special chars in between the column speraters 

**Additional context**

**Comment by pkjmesra** [comment]
@sandykools -

The backtest results do get saved under folder "Backtest-Reports" along side "results" folder in the same root folder from where you launched pkscreenercli. The HTML files have the capability to sort/filter etc. See, for example. https://pkjmesra.github.io/PKScreener/BacktestReports.html

**Comment by pkjmesra** [comment]
@sandykools - I've thought about it and eventually decided to provision an alternative. If you set the configuration in the pkscreener.ini file
```
alwaysExportToExcel = y
```
and then run backtests, it will ask you if you want to save/export the backtest results into excel file. If you choose to say yes (y), it will export all the backtest results for the selected category into <current working directory>/results/Reports/

Please note that the default backtest reports in the html format are pushed into <current working directory>/Backtest-Reports/

I hope this helps. This will become available in the next build.
