### ISSUE TITLE
Progress bar required during scans and processing

### ISSUE THREAD

**Issue by anuragc2001** [pkjmesra/PKScreener#182]
**Is your feature request related to a problem? Please describe.**
- It'd be nicer if we could have a progress bar while scanning and processing the data.

**Describe the solution you'd like**
- maybe a  #############--------------- type progress bar would help.

**Comment by pkjmesra** [comment]
@anuragc2001
We already show progress bar during the scanning and processing of data. Is there some place where you noticed it missing, please let us know.

**Comment by anuragc2001** [comment]
Sure, let me give a thorough check, and I'll note the places required.

**Comment by pkjmesra** [comment]
Thanks much for pointing it out that several long running tasks were still missing "some" progress update. This has been majorly fixed now with the next upcoming release.

Fixed: c307cb459ab69f2cd5ec551b6a176bb29825671f
