### ISSUE TITLE
Build an option to just enter stock name and it can come back with which all scans had that stock in results. Allow user to select how many days far back does the option need to show - example 7 for past 7 days data

### ISSUE THREAD

**Issue by Meehir5** [pkjmesra/PKScreener#186]
Build an option to just enter stock name and it can come back with which all scans had that stock in results. Allow user to select how many days far back does the option need to show - example 7 for past 7 days data

![image](https://github.com/user-attachments/assets/3be0794f-972e-4a4a-a53b-53b25025270c)

**Comment by pkjmesra** [comment]
@Meehir5 - This will be available in build 578 and above
