### ISSUE TITLE
Please enable the Hyperlinks for the Stocks for the downloaded reports (Scanners, Back tests) 

### ISSUE THREAD

**Issue by sandykools** [pkjmesra/PKScreener#188]
**Is your feature request related to a problem? Please describe.**
When the back test results or other results are downloaded/saved in xlsx, there are no hyperlinks for the stock names. 
Please enable hyperlinks for the same as in the console outputs.

**Describe the solution you'd like**
When clicked on the Stock name in Excel, it should automatically redirect to Tradingview or any other Charting Site 

**Describe alternatives you've considered**
NA

**Additional context**
NA
![image](https://github.com/user-attachments/assets/ebe41f1c-cecc-4920-86da-c2159e70c4a3)

**Comment by gauravagrawal13** [comment]
Something like this while exporting:
=HYPERLINK("https://in.tradingview.com/chart/hobIb8CN/?symbol=NSE:" &A2, "View " & A2 & " Chart")
=HYPERLINK("https://in.tradingview.com/chart/hobIb8CN/?symbol=NSE:" &A#, "View " & A# & " Chart")

cc @pkjmesra

**Comment by pkjmesra** [comment]
Hi @sandykools - This should be available in the next to next build. Please try with build **0.45.20240919.573** and above.
