### ISSUE TITLE
Sudden stop in results

### ISSUE THREAD

**Issue by keithevans786** [pkjmesra/PKScreener#190]
I was running VCP scanner & had pinned it, it started from 9:47 & stopped giving results since 10:12.
Please find the image attested 

![IMG_20240917_165822_336.jpg](https://github.com/user-attachments/assets/8c40449d-0126-4aec-ac5a-77be861bdefc)

**Comment by pkjmesra** [comment]
@keithevans786 - Is this still happening ?

**Comment by pkjmesra** [comment]
@keithevans786 - Is this still happening ? Waiting for your response?

**Comment by keithevans786** [comment]
All good now. Thanks alot
