### ISSUE TITLE
Excel Request

### ISSUE THREAD

**Issue by keithevans786** [pkjmesra/PKScreener#194]
Hey, I came with an idea to keep the record in local drive while the "PINNED" scanner is running & showing results continuously there is no record that a person can keep that which stocks were given at what time. 

Kindly enable live excel exporting as an optional feature, it'd be disabled by default if someone wants to keep record then they can manually enable it. This feature would be helpful for people to keep track at the times when stocks perform. 

The rows in excel should have the record of date & time, and consolidation range. Rest all according to the the default data provided by the screener.

I hope this happens soon. God bless your great work 😊

**Comment by pkjmesra** [comment]
@keithevans786 - this is done. You should see all the data you need by turning on the setting in pkscreener.ini
```
alwaysexporttoexcel = y
```
Please note that by default it's turned off to improve performance.
