### ISSUE TITLE
Reset Configuration settings to Default

### ISSUE THREAD

**Issue by sandykools** [pkjmesra/PKScreener#195]
**Is your feature request related to a problem? Please describe.**
Feature request. 

**Describe the solution you'd like**
During testing, we make lot of configuration changes but cannot keep track of them. It would be convenient to have reset or restore to default settings/config.

**Describe alternatives you've considered**
Have copy of config file before making changes and replace it manually. 

**Additional context**

**Comment by pkjmesra** [comment]
@sandykools - If you delete or rename the pkscreener.ini file, and relaunch the pkscreenercli, it will recreate the config file with default values. I hope that helps. 

Alternatively you can also use the option E > to edit the config and then select all default values (just keep pressing <enter>). That will also reset all values to default values.

**Comment by pkjmesra** [comment]
@sandykools - Closing this as resolved because you can always delete the existing pkscreener.ini file and relaunch the app. It will automatically recreate the configs in pkscreener.ini with default values.
