### ISSUE TITLE
Not able to run pkscreenercli.py

### ISSUE THREAD

**Issue by dravidsa** [pkjmesra/PKScreener#196]
the installation was successful but when I try to run pkscreenercli.py from my Mac terminal , I get following error 

Traceback (most recent call last):
  File "/Users/sandeepdravid/PKScreener-main/pkscreener/pkscreenercli.py", line 57, in <module>
    from pkscreener import Imports
ModuleNotFoundError: No module named 'pkscreener'

Can you help. ?

Regards
Sandeep

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pkjmesra** [comment]
@dravidsa - Can you please try and run it from the project root directory ? /Users/sandeepdravid/PKScreener-main/

**Comment by dravidsa** [comment]
Yes I had tried it running from project root but it still gave an error but now I just copied the main cli file from subdirectory into main and then ran and it worked.

Thanks . Looks like a great tool , look forward to use it .

Regards
Sandeep

________________________________

**Comment by pkjmesra** [comment]
Updated the documentation to reflect the same.
