### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by devfinwiz** [pkjmesra/PKScreener#20]
Wanna collaborate on a new finance project together? Drop a message on linkedin in case you are interested after a quick reply here.

**Comment by pkjmesra** [comment]
@devfinwiz - What project? Can you share a synopsis or the GitHub repo, if that's a public repo?

**Comment by devfinwiz** [comment]
Hi @pkjmesra ,
https://github.com/devfinwiz/Fin-Maestro-Web

I was planning to improvise this project such that it is correctly deployable with ease along with frontend. Also, maybe a new project to build a FastApi for Fin-Maestro. Let me know what you think about it...
