### ISSUE TITLE
Making Results Easier to Read: "Find a stock in scanners"

### ISSUE THREAD

**Issue by gauravagrawal13** [pkjmesra/PKScreener#204]
When using the option "Find a stock in scanners > Screen stocks by stock names[1]," the screener shows the codes for all scanners that include the selected stock. However, it’s hard to understand what each code means without going back to the scanners to check their descriptions.

A better approach would be to show the full scanner name along with the code or make the information easier to read. This would make it quicker and easier to understand the stock’s details without constantly switching between the codes and their descriptions.

![Capture](https://github.com/user-attachments/assets/2e5c1a7a-e83d-45d5-b159-0426de7452e8)

**Comment by pkjmesra** [comment]
Thanks @gauravagrawal13 ! I was thinking about it as well! I'll get this taken up.

**Comment by pkjmesra** [comment]
@gauravagrawal13 - How does this look? Better ?

<img width="1479" alt="Screenshot 2024-09-30 at 6 10 53 PM" src="https://github.com/user-attachments/assets/6c44fe01-6857-44fe-9ba0-64b5b5d5cdbe">

**Comment by pkjmesra** [comment]
Fixed in build # 607.

**Comment by gauravagrawal13** [comment]
LGTM :)
