### ISSUE TITLE
Unalbe install requirements from requirements.txt file as some requirements asking low python version and some asks high python version

### ISSUE THREAD

**Issue by Saikishorkhadge** [pkjmesra/PKScreener#62]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Saikishorkhadge** [comment]
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.10,<4.0; 0.1.1 Requires-Python >=3.10,<4.0; 0.1.2 Requires-Python >=3.10,<4.0; 0.1.3 Requires-Python >=3.10,<4.0; 0.1.4 Requires-Python >=3.10,<4.0; 0.1.6 Requires-Python >=3.10,<4.0; 0.1.7 Requires-Python >=3.10,<4.0; 0.1.8 Requires-Python >=3.10,<4.0
ERROR: Could not find a version that satisfies the requirement advanced_ta (from versions: none)
ERROR: No matching distribution found for advanced_ta

**Comment by Saikishorkhadge** [comment]
I just got the problem with requirement advanced_ta

**Comment by Saikishorkhadge** [comment]
Traceback (most recent call last):
  File "c:\Users\saiki\PKScreener\pkscreener\pkscreenercli.py", line 52, in <module>
    from PKDevTools.classes.PKDateUtilities import PKDateUtilities
  File "C:\Users\saiki\AppData\Local\Programs\Python\Python39\lib\site-packages\PKDevTools\classes\PKDateUtilities.py", line 36, in <module>
    class PKDateUtilities:
  File "C:\Users\saiki\AppData\Local\Programs\Python\Python39\lib\site-packages\PKDevTools\classes\PKDateUtilities.py", line 82, in PKDateUtilities
    def nextTradingDate(d1:datetime.datetime|str=None, days=1):
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by pkjmesra** [comment]
@Saikishorkhadge - You need at least python 3.10. I'd advise using python 3.11 for some of the dependencies like lorenzian scans.
"|" was added in python 3.10, so not available in python 3.9 or lower.
