### ISSUE TITLE
front end doesnt contain the carious screener names,so dont know which number to type

### ISSUE THREAD

**Issue by Kasi72** [pkjmesra/PKScreener#91]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pkjmesra** [comment]
@Kasi72 - Which frontend are you referring to ? Did you mean the telegram bot or the command line application?
In both of them you can choose the index and then screener names.

For CLI:

Step 1: Choose the menu option (say, Scanners)
<img width="1204" alt="Step1" src="https://github.com/pkjmesra/PKScreener/assets/1358101/6d421607-293c-4c39-a165-dc764baff178">

Step 2: Choose your index (Say, All stocks or Nifty 50 )
<img width="1202" alt="Step2" src="https://github.com/pkjmesra/PKScreener/assets/1358101/2b9e1e7c-06bb-42f9-a4be-e5987f105726">

Step 3: Choose the scanner type you want to run.
<img width="1204" alt="Step3" src="https://github.com/pkjmesra/PKScreener/assets/1358101/dfde7d63-e666-4858-acec-4e12e1e782ed">

For Telegram bot:, you can simply follow the prompts and then submit your scan request.

**Comment by pkjmesra** [comment]
Closing the issue now. the most recent release also forces the background color to be black and foreground color to be white for windows/Linux.
